"""Design 파이프라인 단계 6종 — PipelineStep 구현 (T3 P2, spec §4.2).

구 DesignHarness._s0_setup~_s3_final(T3 P1 시점 harness_design.py:302-527)의
행동 보존 이동. S2aVisual만 매체 액터(image_provider)를 생성자 주입받고,
나머지 단계는 무상태(턴 입력은 전부 StepContext로 — 체크리스트 ⑩).

S3 critic 단일화(T1 백로그 ②): S3Final.run이 채점 raw를 ctx.cache에 무조건부
기록하고 critic_gate가 재사용 — 같은 턴 LLM 채점 2회→1회. cache는 턴 스코프
(StepContext가 턴마다 새로 생성)라 regenerate 재실행과 안전 공존(run이 덮어씀).
"""
from __future__ import annotations

import json
import os
import re

from ...core.fonts import looks_like_font_name
from ...core.grounding import build_corpus, find_ungrounded
from ...core.lang import normalize_languages
from ...core.parsing import parse_frontmatter as _frontmatter, parse_json_block, read_json_node
from ...core.visual_rules import enrich_visual_metadata, visual_compliance_summary
from ...providers.base import Message
from ..critic import CriticVerdict
from ..harness import HarnessResult
from ..pipeline import DONE, GateCheck, PipelineStep, StepContext
from ..prompt import PromptSpec
from .layout_engine import DEFAULT_SEMANTIC, _dims, build_layout
from .prompts import (PERSONA, S1_INSTR, S2B_INSTR, SEMANTIC_LAYOUT_INSTR,
                      TEXTFREE_VISION_INSTR, build_hero_prompt, build_vision_instr)
from .scoring import RUBRIC, run_critic

# S3 채점 raw의 턴 캐시 키 — S3Final.run이 기록, critic_gate가 재사용(백로그 ②).
S3_CRITIC_CACHE = "s3_critic"

# S2a 비전 검증 findings의 턴 캐시 키 — S2aVisual.run이 기록, critic_gate가 재사용(S3 전례).
S2A_VISION_CACHE = "s2a_vision"

MAX_BAKE_ATTEMPTS = 2   # 베이크 텍스트 정확성 재생성 상한(내부 루프). 외부 게이트 재생성과 합성.

# 금리 카드 그라운딩: factsheet에서 카드에 넣을 금융 수치를 결정론적으로 뽑는다. S2b 카피가
# 런별로 숫자를 누락해도(실측 변동성) 여기서 진실 원천을 고정 — 베이크 지시·비전 검증·정적
# 저장(rate_card 노드)에 공통 사용해 금융수치 환각(예: 3.5%→5.0%)을 입력 그라운딩+검증으로 차단.
_FACT_FIELDS = [("product_name", "상품명"), ("interest_rate", "기본금리"),
                ("max_rate", "최고금리"), ("prime_rate", "우대금리"),
                ("term", "가입기간"), ("min_amount", "최소가입금액")]


def _facts_from_factsheet(fs: dict) -> dict:
    """factsheet → 카드용 수치 dict(존재하는 키만, 문자열화). 진실 원천."""
    out = {}
    for key, label in _FACT_FIELDS:
        v = (fs or {}).get(key)
        if v:
            out[label] = str(v)
    return out


def _facts_line(facts: dict) -> str:
    return " · ".join(f"{label} {val}" for label, val in facts.items())


def _benefit_chips(facts: dict) -> list:
    """혜택 아이콘 칩 라벨(그라운딩) — factsheet 값에서만 파생, 창작 금지.
    밀도 격차(image copy 6의 아이콘 칩 행) 해소용. 역할 분리로 중복 회피:
    금리 카드=헤드라인 금리(기본·최고)를 크게, 칩 행=가입 조건(우대·기간·금액)을
    아이콘과 함께 요약. 라벨은 여기서 결정론적으로 고정해 베이크 환각을 차단한다."""
    chips = []
    up = facts.get("우대금리")
    if up:
        # 값이 이미 '우대'로 시작하면 접두 생략(중복 '우대금리 우대' 방지 — 실측 교정).
        chips.append(up if up.lstrip().startswith("우대") else f"우대금리 {up}")
    if facts.get("가입기간"):
        chips.append(f"가입기간 {facts['가입기간']}")
    if facts.get("최소가입금액"):
        # 값에 이미 '부터'가 있으면 중복 접미 생략.
        amt = facts["최소가입금액"]
        chips.append(amt if amt.rstrip().endswith("부터") else f"{amt}부터")
    return chips


def _rich_enabled() -> bool:
    """RICH_VECTOR_CHROME flag — on이면 S2a가 텍스트프리 히어로+벡터 크롬 spec을 생성.
    off(기본)면 검증된 베이크 경로 그대로(spec §8 폴백). 매 호출 env 조회(테스트 monkeypatch)."""
    return (os.getenv("RICH_VECTOR_CHROME") or "").strip().lower() in {"1", "true", "yes", "on"}

# 표준 종횡비 후보 — material_matrix의 size에서 근접 매핑.
_STD_ASPECTS = [(1, 1, "1:1"), (4, 5, "4:5"), (5, 4, "5:4"), (3, 4, "3:4"),
                (4, 3, "4:3"), (9, 16, "9:16"), (16, 9, "16:9"),
                (2, 3, "2:3"), (3, 2, "3:2")]


def _aspect_from_matrix(matrix) -> str | None:
    """material_matrix 첫 항목의 size/format/aspect에서 종횡비 추론.

    creative_direction에 aspect가 없을 때 폴백 — "1080×1920 (9:16)"→9:16,
    "1080×1080"→1:1. 명시 비율(예: 9:16)이 있으면 우선, 없으면 픽셀 치수를 표준비로 근사.
    """
    for m in (matrix or []):
        if not isinstance(m, dict):
            continue
        for field in ("aspect", "size", "format"):
            txt = str(m.get(field, ""))
            rm = re.search(r"\b(\d{1,2})\s*:\s*(\d{1,2})\b", txt)        # 명시 비율 우선
            if rm:
                return f"{int(rm.group(1))}:{int(rm.group(2))}"
            dm = re.search(r"(\d{2,5})\s*[×xX*]\s*(\d{2,5})", txt)        # 픽셀 치수
            if dm:
                w, h = int(dm.group(1)), int(dm.group(2))
                if w > 0 and h > 0:
                    ratio = w / h
                    return min(_STD_ASPECTS, key=lambda a: abs(a[0] / a[1] - ratio))[2]
    return None


# I5: 기본 고지 floor — 금융광고 유의문구 + AI 생성 고지(언어별, 미지원은 ko 폴백).
# 상품별 필수 고지(예금자보호 등)는 plan.disclosures→DISCLOSURE_DISPLAY로 이 위에 얹힌다.
# 이 floor는 상품과 무관하게 항상 안전한 표준 문구라 "고지 없음"을 기본적으로 방지한다.
NOTICES = {"ko": "가입 전 상품설명서·약관 확인 필수. 본 이미지는 AI로 생성되었습니다.",
           "en": "Review product terms before signing up. This image was generated by AI.",
           "vi": "Đọc kỹ điều khoản trước khi đăng ký. Hình ảnh này được tạo bởi AI.",
           "zh": "签约前请确认产品说明书及条款。本图片由AI生成。"}

# 필수 법령 고지의 언어별 표시문(번역). 표시문이 있는 언어에만 부착하고,
# 없는 언어는 고지를 '누락'시켜(무번역 한국어 법령문이 외국어 포스터에 새지 않게)
# 검토(R2)가 잡아 교정을 유도한다. severity.DISCLOSURE_I18N(탐지 키워드)와 짝.
# demo: ko·en만 표시문 보유 → vi/zh는 예금자보호 고지 누락(spec §2 위반 #4 스테이징).
DISCLOSURE_DISPLAY = {
    "예금자보호법에 따라 5천만원까지 보호": {
        "ko": "예금자보호법에 따라 5천만원까지 보호",
        "en": "Protected up to KRW 50M under the Depositor Protection Act.",
    },
}


def _bundled_logo() -> bytes:
    """번들 공식 JB금융 로고(국문가로조합 시그니처) PNG 바이트를 로드.

    히어로 텍스트는 AI가 베이크하지만 공식 로고는 정확성이 필수라 결정론 오버레이로 핀한다
    (S2cBrand가 VFS에 기록 + layout_spec logo 슬롯의 asset_ref로 노출 → 프론트가 image로 렌더)."""
    p = os.path.join(os.path.dirname(__file__), "..", "..", "references", "design",
                     "jb-logo-signature-h.png")
    with open(p, "rb") as f:
        return f.read()


def load_references() -> list[dict]:
    """번들 레퍼런스 레이아웃 로드 (구 _load_references — 경로는 app/references/design)."""
    d = os.path.join(os.path.dirname(__file__), "..", "..", "references", "design")
    out = []
    for fn in sorted(os.listdir(d)):
        if fn.endswith(".json"):
            with open(os.path.join(d, fn), encoding="utf-8") as f:
                out.append(json.load(f))
    return out


def _visual_gate(raw: dict) -> GateCheck:
    """7항목 raw 채점 → GateCheck (구 _critic_gate S1/S3 분기의 봉투 변환부)."""
    env = CriticVerdict.from_scores(raw)
    return GateCheck(passed=env.passed, critic=env.to_dict())


class S0Setup(PipelineStep):
    """plan.md frontmatter → design tokens + material_matrix + languages (구 _s0_setup)."""

    name = "S0"
    gated = False

    def run(self, ctx: StepContext) -> HarnessResult:
        base = ctx.base
        plan = ctx.store.get(f"/{ctx.req.run_id}/brainstorming/plan.md")
        fm = _frontmatter(plan.content_text if plan else "")
        cd = fm.get("creative_direction") or {}
        matrix = fm.get("material_matrix", [])
        # creative_direction은 구조형(palette/font/grid/aspect) 또는 실 브레인스토밍의 서술형
        # (concept/visual_mood/color_palette/typography)로 올 수 있다 — 둘 다 수용해 빈 tokens로
        # 디자인이 브랜드 방향을 잃지 않게 한다. aspect 미기재 시 material_matrix에서 추론.
        # typography는 폰트명일 때만 font로 폴백한다. 실 브레인스토밍은 typography를
        # 서술 문장으로 쓰는데, 그대로 font에 넣으면 design-system 프리뷰 CSS font-family로
        # 새서 깨진다. 서술형 typography는 아래 루프에서 tokens["typography"]로 별도 보존됨.
        _typo = cd.get("typography")
        tokens = {
            "palette": cd.get("palette") or [],
            "font": cd.get("font") or (_typo if looks_like_font_name(_typo) else None),
            "grid": cd.get("grid"),
            "aspect": cd.get("aspect") or _aspect_from_matrix(matrix) or "1:1",
        }
        for k in ("concept", "visual_mood", "color_palette", "typography"):
            if cd.get(k):
                tokens[k] = cd[k]    # 서술형 브랜드 방향 → S1 styling 힌트(색·폰트·톤)
        ctx.store.put(f"{base}/design-system/tokens.json",
                      json.dumps(tokens, ensure_ascii=False), source="marker",
                      mime="application/json")
        ctx.store.put(f"{base}/_material_matrix.json",
                      json.dumps(matrix, ensure_ascii=False),
                      source="marker", mime="application/json")
        # 실 LLM은 languages를 객체 리스트([{code:...}])로 쓸 수 있어 문자열 코드로 정규화.
        # (안 하면 S2cBrand/S3Final의 NOTICES.get/copy.get가 dict 키 → TypeError로 크래시.)
        ctx.state["languages"] = normalize_languages(fm.get("languages"))
        return HarnessResult(
            text="디자인 토큰을 확정했습니다. Rough 단계로 진행합니다.",
            output_path=f"{base}/design-system/tokens.json",
            meta={"source": "marker", "step": self.name},
            events=[{"type": "artifact", "path": f"{base}/design-system/tokens.json"}])


class S1Rough(PipelineStep):
    """레퍼런스+tokens → layout_spec JSON (구 _s1_rough). 시각 critic 게이트(비캐시)."""

    name = "S1"
    gated = True

    def run(self, ctx: StepContext) -> HarnessResult:
        base = ctx.base
        tokens = ctx.store.get(f"{base}/design-system/tokens.json")
        refs = load_references()
        # 조립 순서(D6): persona → [S1 Rough] 지시 → [tokens] → [references] — 인라인 시절과 동일.
        pspec = PromptSpec(
            persona=PERSONA,
            constraints=[S1_INSTR],
            references=[f"\n[tokens]\n{tokens.content_text if tokens else '{}'}",
                        f"\n[references]\n{json.dumps(refs, ensure_ascii=False)}"],
            studio="design", step=self.name)
        resp = ctx.provider.complete([Message("user", ctx.req.user_prompt or "러프 시작")],
                                     system=pspec.assemble(), meta=pspec.meta)
        data = parse_json_block(resp.text)
        spec = data.get("layout_spec") or {}
        # 실 LLM이 font_px를 생략해도 R-VIS-1(글자크기 비율)이 동작하도록 bbox 높이로 보강(결정론).
        enrich_visual_metadata(spec)
        ctx.store.put(f"{base}/rough/layout.spec.json",
                      json.dumps(spec, ensure_ascii=False), source="marker",
                      mime="application/json")
        return HarnessResult(text=data.get("reply", "러프 완성"),
            output_path=f"{base}/rough/layout.spec.json",
            meta={"source": "marker", "step": self.name},
            events=[{"type": "artifact", "path": f"{base}/rough/layout.spec.json"}])

    def critic_gate(self, ctx: StepContext) -> GateCheck:
        # 구 _critic_gate S1 분기 — 매 판정마다 신선 채점(bypass 1회 재생성과 짝, 비캐시).
        spec = read_json_node(ctx.store, f"{ctx.base}/rough/layout.spec.json")
        return _visual_gate(run_critic(ctx.provider, spec))


class S2aVisual(PipelineStep):
    """비주얼 PNG 생성 + 비전 검증 게이트 — 매체 액터 생성자 주입 (구 _s2a_visual).

    run이 review_image로 텍스트누출·인물왜곡·safe zone을 점검해 findings를 cache에
    무조건부 기록(S3_CRITIC_CACHE 전례), critic_gate가 재사용. critical만 게이트 차단
    (warning은 자문). 비전 미지원/실패는 fail-open(빈 findings + meta.vision_failed).
    """

    name = "S2a"
    gated = True

    def __init__(self, image_provider) -> None:
        self._image_provider = image_provider   # 턴-불변 의존성(체크리스트 ⑩) — generate_image + review_image

    def run(self, ctx: StepContext) -> HarnessResult:
        base = ctx.base
        spec = read_json_node(ctx.store, f"{base}/rough/layout.spec.json")
        concept = spec.get("visual_concept", "금융 브랜드 추상 배경")
        aspect = spec.get("aspect", "1:1")
        lang = (ctx.state.get("languages") or ["ko"])[0]
        copy = (spec.get("copy") or {}).get(lang, {})
        # 금리 카드 그라운딩(진실 원천): factsheet 수치를 S2b 카피 변동성과 무관하게 고정한다.
        # 정적 노드(rate_card)로 저장(사용자 제안 — copy/리뷰가 정적 정답 참조) + 베이크 지시 +
        # 비전 검증에 공통 주입해 금융수치 환각을 이중 방어(입력 그라운딩 + 출력 검증).
        plan = ctx.store.get(f"/{ctx.req.run_id}/brainstorming/plan.md")
        facts = _facts_from_factsheet(_frontmatter(plan.content_text if plan else "").get("factsheet") or {})
        facts_line = _facts_line(facts)
        if facts:
            ctx.store.put(f"{base}/design-system/components/rate_card/{lang}.json",
                          json.dumps(facts, ensure_ascii=False), source="marker",
                          mime="application/json", meta={"lang": lang, "grounds": "factsheet"})
        # rich 분기(spec 2026-07-02 §3.1): flag on이면 텍스트프리 히어로+벡터 크롬 spec으로.
        # off(기본)면 아래 검증된 베이크 경로 그대로. rate_card 정적 저장은 위에서 이미 실행돼
        # 두 경로 공통 그라운딩 진실 원천으로 남는다(rich에서도 유지).
        if _rich_enabled():
            return self._run_rich(ctx, spec, copy, facts, aspect, lang)
        base_prompt = self._bake_prompt(concept, copy, spec.get("slots"), facts_line,
                                        _benefit_chips(facts))
        png, findings, vision_failed, fallback = self._bake_with_retry(base_prompt, aspect, copy, facts_line)
        path = f"{base}/design-system/components/visual/v1.png"
        ctx.store.put(path, png, source="gemini", mime="image/png",
                      meta={"concept": concept, "aspect": aspect, "image_fallback": fallback})
        spec.setdefault("visual_by_lang", {})[lang] = "design-system/components/visual/v1.png"
        # 추가 언어: image-edit 변형(같은 비주얼 유지, 텍스트만 교체). 비차단(경고+에디터 교정).
        for vlang in (ctx.state.get("languages") or ["ko"])[1:]:
            vcopy = (spec.get("copy") or {}).get(vlang, {})
            try:
                var_png = self._image_provider.generate_image(self._edit_prompt(vcopy),
                                                              aspect=aspect, image=png)
            except Exception:
                continue   # 변형 실패는 무시(주 언어는 이미 확보) — 에디터 안전망
            self._vision_check(var_png, vcopy)   # findings는 경고용(게이트 비차단)
            vpath = f"{base}/design-system/components/visual/v1.{vlang}.png"
            ctx.store.put(vpath, var_png, source="gemini", mime="image/png",
                          meta={"lang": vlang, "edited_from": "v1.png"})
            spec["visual_by_lang"][vlang] = f"design-system/components/visual/v1.{vlang}.png"
        ctx.store.put(f"{base}/rough/layout.spec.json", json.dumps(spec, ensure_ascii=False),
                      source="marker", mime="application/json")
        ctx.cache[S2A_VISION_CACHE] = findings
        text = ("비주얼을 생성했습니다." if not fallback else
                "실 이미지 생성에 실패해 대체 비주얼(그라데이션)을 사용했습니다. "
                "실 이미지는 GOOGLE_API_KEY 설정이 필요합니다.")
        return HarnessResult(text=text, output_path=path,
            meta={"source": "gemini", "step": self.name,
                  "image_fallback": fallback, "vision_failed": vision_failed},
            events=[{"type": "artifact", "path": path}])

    def _run_rich(self, ctx, spec, copy, facts, aspect, lang):
        """rich 경로(spec 2026-07-02 §3.1): 텍스트프리 히어로 → vision 의미 레이아웃 →
        layout_engine 결정론 bbox → spec을 vector_chrome으로 갱신. 베이크 경로와 병렬."""
        base = ctx.base
        mood_hint = ""
        tokens = read_json_node(ctx.store, f"{base}/design-system/tokens.json")
        if tokens.get("visual_mood"):
            mood_hint = str(tokens["visual_mood"])
        hero_prompt = build_hero_prompt(spec.get("visual_concept", "금융 브랜드 배경"), mood_hint)
        png, findings, vision_failed, fallback = self._hero_with_retry(hero_prompt, aspect)
        path = f"{base}/design-system/components/visual/v1.png"
        ctx.store.put(path, png, source="gemini", mime="image/png",
                      meta={"render_mode": "vector_chrome", "image_fallback": fallback})
        semantic = self._semantic_layout(png)
        layout = build_layout(semantic, aspect, copy, facts)
        # spec 갱신: slots 교체 + render_mode. aspect/visual_concept/copy 등 나머지 보존.
        # 히어로는 프론트가 background 슬롯으로만 그린다(assembleScenes는 없으면 안 만든다) —
        # engine slots가 background를 방출하지 않으므로 기존 슬롯에서 찾아 보존, 없으면 생성해
        # 앞에 붙인다. logo 슬롯(S2c 핀)도 같은 패턴으로 보존해 다른 재실행 경로(게이트 regenerate 등)를
        # 방어한다. bbox 높이는 aspect에서 계산(_dims 재사용). asset_ref는 visual_by_lang 우선의 폴백.
        W, H = _dims(aspect)
        prev = spec.get("slots") or []
        bg = next((s for s in prev if s.get("role") == "background"), None)
        if bg is None:
            bg = {"role": "background", "z": 0,
                  "bbox": {"x": 0, "y": 0, "w": W, "h": H},
                  "asset_ref": "design-system/components/visual/v1.png"}
        logo = next((s for s in prev if s.get("role") == "logo"), None)
        spec["slots"] = [bg] + layout["slots"] + ([logo] if logo else [])
        spec["render_mode"] = layout["render_mode"]
        # 텍스트 프리 히어로 = 언어 무관 → 전 언어가 같은 비주얼(변형 생성 불필요·비용 0).
        vb = spec.setdefault("visual_by_lang", {})
        for vlang in (ctx.state.get("languages") or [lang]):
            vb[vlang] = "design-system/components/visual/v1.png"
        ctx.store.put(f"{base}/rough/layout.spec.json", json.dumps(spec, ensure_ascii=False),
                      source="marker", mime="application/json")
        ctx.cache[S2A_VISION_CACHE] = findings
        text = ("히어로와 벡터 레이아웃을 생성했습니다." if not fallback else
                "실 이미지 생성에 실패해 대체 비주얼을 사용했습니다.")
        return HarnessResult(text=text, output_path=path,
            meta={"source": "gemini", "step": self.name, "render_mode": "vector_chrome",
                  "image_fallback": fallback, "vision_failed": vision_failed},
            events=[{"type": "artifact", "path": path}])

    def _hero_with_retry(self, hero_prompt, aspect):
        """텍스트프리 히어로 생성 + 텍스트누출 게이트(critical→재생성, MAX_BAKE_ATTEMPTS)."""
        feedback = ""
        png, findings, vision_failed, fallback = None, [], False, False
        for _ in range(MAX_BAKE_ATTEMPTS):
            prompt = hero_prompt + (f"\n[교정] {feedback}" if feedback else "")
            try:
                png = self._image_provider.generate_image(prompt, aspect=aspect)
            except Exception:
                from ...core.placeholder_image import placeholder_png
                return placeholder_png(aspect), [], False, True
            try:
                resp = self._image_provider.review_image(png, TEXTFREE_VISION_INSTR, mime="image/png")
                findings = parse_json_block(resp.text).get("findings") or []
            except Exception:
                vision_failed = True   # fail-open(기존 게이트 정책과 동일)
                return png, [], vision_failed, fallback
            crit = [f for f in findings if f.get("severity") == "critical"]
            if not crit:
                return png, findings, vision_failed, fallback
            feedback = "; ".join(f.get("evidence", "") for f in crit)
        return png, findings, vision_failed, fallback

    def _semantic_layout(self, png):
        """vision 의미 레이아웃(스키마 검증→1회 재시도→DEFAULT_SEMANTIC 폴백)."""
        for _ in range(2):
            try:
                resp = self._image_provider.review_image(png, SEMANTIC_LAYOUT_INSTR, mime="image/png")
                sem = parse_json_block(resp.text)
            except Exception:
                sem = None
            if isinstance(sem, dict) and isinstance(sem.get("clear_zones"), list) \
                    and sem.get("mood") in ("youth", "premium", "campaign"):
                return sem
        return DEFAULT_SEMANTIC

    def _bake_prompt(self, concept: str, copy: dict, slots: list | None = None,
                     facts: str = "", chips: list | None = None) -> str:
        lines = [concept,
                 "다음 문구를 디자인 요소로 **정확히** 렌더하세요(오타·누락 금지):"]
        # 슬롯별 색·크기를 그대로 넘긴다 — 안 넘기면 모델이 임의로 한 가지 어두운 색만
        # 써 텍스트가 단조로워진다(실측 피드백). layout_spec의 color/font_px를 명시.
        by_role = {s.get("role"): s for s in (slots or [])
                   if s.get("role") in ("headline", "body", "cta")}
        for k in ("headline", "body", "cta"):
            if copy.get(k):
                s = by_role.get(k) or {}
                hint = ""
                if s.get("color"):
                    hint = f" (색 {s['color']}"
                    hint += f", 약 {int(s['font_px'])}px 굵게)" if s.get("font_px") else ")"
                lines.append(f"- {k}: {copy[k]}{hint}")
        lines.append(
            "색 위계를 살리세요: 헤드라인·CTA는 브랜드 포인트 컬러로 뚜렷한 색 대비를 주고, "
            "CTA는 버튼처럼 눈에 띄게. 한 가지 어두운 색으로 단조롭게 처리하지 마세요.")
        # 폰트 단조로움 해결(실측 피드백): 모든 글자가 같은 굵기·크기라 밋밋. 굵기·크기 대비로
        # 편집 디자인다운 타이포 위계를 명시.
        lines.append(
            "타이포그래피는 위계와 리듬을 분명히 주세요: 헤드라인은 굵고 임팩트 있는 "
            "**디스플레이 웨이트**, 강조 숫자(금리)는 가장 크고 굵게, 라벨·부가조건·바디는 "
            "가벼운 본문 웨이트로 두어 **굵기 대비(weight contrast)와 크기 단계**(헤드라인 > "
            "금리 숫자 > 라벨 > 바디)를 뚜렷이 하세요. 전부 같은 굵기·크기로 균일하게 처리하지 "
            "말고, 실제 광고처럼 강약이 있는 세련된 서체 운용으로 마감하세요.")
        lines.append(
            "오버레이 세이프존을 반드시 확보하세요: **좌상단 모서리(로고 자리)는 밝은 오프화이트 "
            "단색으로 깨끗이 비우고**(어두운 배경이 오면 로고가 묻힘), **최하단 가로 영역은 브랜드 "
            "색의 솔리드 푸터 밴드로 디자인**하되(포스터의 일부처럼 자연스럽게 어울리게, 사진 위에 "
            "덧댄 느낌이 아니라 하단이 밴드로 마감되도록) 그 밴드 안은 **텍스트·요소 없이 비워** 법령 "
            "고지 오버레이 자리로 남기세요. CTA 버튼은 이 푸터 밴드 위쪽에 충분한 여백을 두고 배치해 "
            "겹치지 않게 하세요.")
        # 부수 텍스트 footgun 차단: 모델이 폰 화면·간판·빈 영역에 깨진 잔글씨나
        # 'LOGO' 같은 placeholder를 멋대로 굽는다(실측 2026-06-30). 명시 카피만 허용.
        lines.append(
            "위에 명시한 문구만 텍스트로 렌더하세요. 그 외 어떤 텍스트·숫자·앱/UI 화면·"
            "간판·라벨·문서·워터마크·임의의 로고도 만들지 마세요. 인물이 든 기기(폰·노트북·"
            "태블릿) 화면과 배경 소품은 글자 없이(블랭크) 두세요 — 가짜 잔글씨 절대 금지.")
        # 아트디렉션 플로어: concept 품질과 무관하게 광고급 마감을 보장한다(실측 결과
        # 텍스트 베이크는 완벽하나 전반 룩이 스톡/평면적일 때가 있어 하한선을 명시).
        lines.append(
            "전체를 실제 금융 브랜드 광고 수준으로 마감하세요: 전문 광고 사진 품질의 "
            "자연광·시네마틱 라이팅과 얕은 심도, 편집 디자인다운 그리드·여백·타이포 위계, "
            "고급스럽고 신뢰감 있는 색보정. 저해상·클립아트·밋밋한 스톡 느낌은 피하세요.")
        # 정보 밀도(실측 피드백: GPT 딸깍 대비 위젯·컨테이너가 없어 조잡). 새 텍스트를
        # 만들지 않고 '레이아웃·도형·컨테이너'로만 밀도를 낸다 — 명시 카피(특히 body의
        # 금리·기간·금액)를 밋밋한 줄이 아니라 구조화된 하이라이트로 디자인하게 지시.
        lines.append(
            "정보 밀도를 실제 은행 포스터 수준으로 높이세요(가장 중요): body의 금리·기간·금액은 "
            "밋밋한 한 줄이 아니라 **금리 하이라이트 카드**로 디자인하세요 — 둥근 모서리 컨테이너"
            "(반투명 화이트 또는 브랜드 틴트, 부드러운 그림자) 안에 핵심 숫자(금리 %)를 가장 크고 "
            "굵게 강조하고, 그 위/아래에 라벨과 부가 조건을 작은 글자로 위계 있게 정렬하세요. "
            "여백·얇은 구분선·악센트 바·포인트 도형·아이콘 형태의 그래픽으로 편집 디자인다운 "
            "리듬과 밀도를 주고, 헤드라인·카드·CTA를 명확한 그리드로 구조화하세요. "
            "**금리 카드는 핵심 금리(기본·최고 %)를 가장 크고 굵게 강조**하고, 가입 기간·최소금액 "
            "등 조건은 아래 혜택 칩 행으로 분리해 정렬하세요(카드와 칩의 역할을 나눠 밀도를 냄). "
            "**단 밀도는 오직 레이아웃·도형·컨테이너·색으로만 내고, 위·아래에 명시한 문구 외의 새로운 "
            "텍스트·숫자·라벨·문장은 절대 만들지 마세요**(빈 카드·의미 없는 잔글씨 금지).")
        # 혜택 아이콘 칩 행(밀도 격차 해소 — image copy 6 수준의 아이콘 조밀도). 라벨은
        # _benefit_chips로 그라운딩(창작 금지)하고, 아이콘은 단순 픽토그램(정확성 불요)만 허용.
        # footgun 가드보다 뒤에 두어 '아래에 명시한 문구'로 허용 범위에 포함시킨다.
        if chips:
            lines.append(
                "금리 카드 아래에 **혜택 아이콘 칩 행**을 배치해 밀도를 높이세요: 아래 각 항목을 "
                "하나의 칩(둥근 컨테이너 또는 구분된 셀)으로 만들고, 각 칩에 항목에 어울리는 "
                "**단순한 라인 픽토그램 아이콘**(우대금리=상승 화살표/플러스, 가입기간=달력, "
                "최소금액=동전/지갑 등)을 단색 선화로 얹어 가로로 균등 정렬하세요. 칩 라벨 텍스트는 "
                "아래 문구를 **한 글자도 바꾸지 말고 정확히 그대로만** 쓰세요(창작·변경·추가 금지): "
                + "  |  ".join(chips))
        # 금융수치 그라운딩(진실 원천 주입): factsheet 값만 정확히 렌더, 창작 금지. S2b 카피가
        # 숫자를 누락해도 gemini가 카드에 넣을 정답을 여기서 못박아 환각(3.5%→5.0%)을 차단.
        if facts:
            lines.append(
                "금리 카드와 모든 수치 표기에는 아래 factsheet 값만 **정확히** 렌더하세요 "
                "(창작·변경·과장 절대 금지, 목록에 없는 금리·금액·기간 숫자는 만들지 말 것): "
                + facts)
        return "\n".join(lines)

    def _edit_prompt(self, copy: dict) -> str:
        lines = ["이 포스터의 텍스트만 다음으로 정확히 교체하고, 인물·배경·구도·색은 그대로 유지:"]
        for k in ("headline", "body", "cta"):
            if copy.get(k):
                lines.append(f"- {k}: {copy[k]}")
        lines.append("교체 문구 외 다른 텍스트·앱/UI 화면·간판·워터마크는 만들지 말고, "
                     "기기 화면·배경 소품은 글자 없이 유지하세요(가짜 잔글씨 금지).")
        return "\n".join(lines)

    def _bake_with_retry(self, base_prompt, aspect, copy, facts=""):
        feedback = ""
        png, findings, vision_failed, fallback = None, [], False, False
        for attempt in range(MAX_BAKE_ATTEMPTS):
            prompt = base_prompt if not feedback else f"{base_prompt}\n이전 시도 교정: {feedback}"
            try:
                png = self._image_provider.generate_image(prompt, aspect=aspect)
                fallback = False
            except Exception:
                from ...core.placeholder_image import placeholder_png
                png = placeholder_png(aspect); fallback = True
                findings, vision_failed = [], True
                break
            findings, vision_failed = self._vision_check(png, copy, facts)
            criticals = [f for f in findings if f.get("severity") == "critical"]
            if not criticals:
                break
            feedback = "; ".join(f.get("evidence", "") for f in criticals)
        return png, findings, vision_failed, fallback

    def _vision_check(self, png: bytes, copy: dict, facts: str = "") -> tuple[list, bool]:
        """review_image로 비전 점검 → (findings, vision_failed). 미지원/실패는 ([], True).

        facts(factsheet 금융수치 정답)를 주면 베이크된 카드 숫자를 대조해 불일치를 critical로
        보고 → _bake_with_retry가 재생성(금융수치 환각 차단의 이빨).
        """
        try:
            resp = self._image_provider.review_image(png, build_vision_instr(copy, facts), mime="image/png")
            return ((parse_json_block(resp.text).get("findings") or []), False)
        except Exception:
            return ([], True)   # 비전 미지원/실패 → fail-open(빈 findings로 통과)

    def critic_gate(self, ctx: StepContext) -> GateCheck:
        # run이 항상 선행 기록하지만 비전은 fail-open이라 방어적 default.
        findings = ctx.cache.get(S2A_VISION_CACHE, [])
        blocking = [f for f in findings if f.get("severity") == "critical"]
        issues = [f.get("evidence", "") for f in blocking]
        return GateCheck(passed=not blocking,
                         critic=CriticVerdict(passed=not blocking, issues=issues).to_dict())


class S2bCopy(PipelineStep):
    """카피 확정 + grounding (구 _s2b_copy). 게이트 = ungrounded 비어야 pass."""

    name = "S2b"
    gated = True

    def run(self, ctx: StepContext) -> HarnessResult:
        base = ctx.base
        plan = ctx.store.get(f"/{ctx.req.run_id}/brainstorming/plan.md")
        fm = _frontmatter(plan.content_text if plan else "")
        corpus = build_corpus(fm.get("factsheet") or {})
        # 조립 순서(D6): persona → [S2b] 지시 → [factsheet] — 인라인 시절과 동일.
        pspec = PromptSpec(
            persona=PERSONA,
            constraints=[S2B_INSTR],
            references=[f"\n[factsheet]\n{json.dumps(fm.get('factsheet') or {}, ensure_ascii=False)}"],
            studio="design", step=self.name)
        resp = ctx.provider.complete([Message("user", ctx.req.user_prompt or "카피 확정")],
                                     system=pspec.assemble(), meta=pspec.meta)
        copy = (parse_json_block(resp.text).get("copy")) or {}
        ungrounded = []
        for lang, fields in copy.items():
            for role in ("headline", "body", "cta"):
                val = (fields or {}).get(role, "")
                ungrounded += find_ungrounded(val, corpus)
                folder = {"headline": "headline", "body": "body", "cta": "cta"}[role]
                ctx.store.put(f"{base}/design-system/components/{folder}/{lang}.txt",
                              val, source="marker", mime="text/plain",
                              meta={"lang": lang, "role": role})
        # 단일 소스: 프론트 어셈블러가 읽는 layout.spec.json["copy"]에 정제 카피를 병합
        # (slots/visual_concept/aspect 등 나머지는 보존).
        spec = read_json_node(ctx.store, f"{base}/rough/layout.spec.json")
        spec.setdefault("copy", {})
        for lang, fields in copy.items():
            spec["copy"].setdefault(lang, {})
            spec["copy"][lang].update(fields or {})
        ctx.store.put(f"{base}/rough/layout.spec.json",
                      json.dumps(spec, ensure_ascii=False), source="marker",
                      mime="application/json",
                      meta={"grounds": {"corpus": "factsheet",
                                        "ungrounded": sorted(set(ungrounded))}})
        return HarnessResult(text="카피를 확정했습니다.",
            output_path=f"{base}/design-system/components/headline",
            meta={"source": "marker", "step": self.name, "ungrounded": sorted(set(ungrounded))},
            events=[{"type": "artifact", "path": f"{base}/design-system/components/headline"}])

    def critic_gate(self, ctx: StepContext) -> GateCheck:
        # 구 _critic_gate S2b 분기 — grounding: ungrounded 수치가 비어야 pass.
        plan = ctx.store.get(f"/{ctx.req.run_id}/brainstorming/plan.md")
        fm = _frontmatter(plan.content_text if plan else "")
        corpus = build_corpus(fm.get("factsheet") or {})
        spec = read_json_node(ctx.store, f"{ctx.base}/rough/layout.spec.json")
        bad = []
        for fields in (spec.get("copy") or {}).values():
            for role in ("headline", "body", "cta"):
                bad += find_ungrounded((fields or {}).get(role, ""), corpus)
        return GateCheck(passed=not bad, critic=CriticVerdict(
            passed=not bad, issues=sorted(set(bad))).to_dict())


class S2cBrand(PipelineStep):
    """브랜드·고지 컴포넌트 배치 (구 _s2c_brand). critic 없음(기본 pass)."""

    name = "S2c"
    gated = True

    def run(self, ctx: StepContext) -> HarnessResult:
        base = ctx.base
        plan = ctx.store.get(f"/{ctx.req.run_id}/brainstorming/plan.md")
        fm = _frontmatter(plan.content_text if plan else "")
        disclosures = fm.get("disclosures") or []
        langs = ctx.state.get("languages", ["ko"])
        notices = {}
        for lang in langs:
            notice = NOTICES.get(lang, NOTICES["ko"])
            # 법령 고지 부착 규칙:
            #  - 표시문(번역) 매핑이 있으면 그 언어로 부착(ko·en 등).
            #  - ko는 매핑이 없어도 원문 고지(한국어)가 그대로 유효 → 원문 부착.
            #    (실 캠페인 plan.md의 임의 disclosures가 ko 포스터에서 통째 사라지는 것 방지.)
            #  - 그 외 언어는 무번역 누락 → 외국어 포스터에 한글이 새지 않고, R2가 누락을 잡아 교정 유도.
            parts = [notice]
            for disc in disclosures:
                localized = DISCLOSURE_DISPLAY.get(disc, {}).get(lang)
                if localized:
                    parts.append(localized)
                elif lang == "ko":
                    parts.append(disc)
            text = " ".join(parts)
            notices[lang] = text
            ctx.store.put(f"{base}/design-system/components/disclosure/{lang}.txt",
                          text, source="marker", mime="text/plain", meta={"lang": lang})
            ctx.store.put(f"{base}/design-system/components/logo/{lang}.txt",
                          "[LOGO]", source="marker", mime="text/plain", meta={"lang": lang})
        # 공식 로고 핀(결정론 오버레이): 번들 PNG 바이트를 VFS에 기록. 히어로 텍스트는 AI가
        # 베이크하지만 공식 로고는 정확성이 필수라 placeholder가 아닌 실 바이트로 박는다.
        logo_path = f"{base}/design-system/components/logo/v1.png"
        ctx.store.put(logo_path, _bundled_logo(), source="marker", mime="image/png")
        # 단일 소스: 프론트 어셈블러가 읽는 layout.spec.json["copy"]에 고지 텍스트를 병합하고,
        # logo 슬롯(asset_ref)을 같은 spec에 추가(slots/visual_concept/aspect/기존 copy 등 나머지는
        # 보존). 한 번의 read/put으로 직렬화 — 별도 read/put 금지(경합·덮어쓰기 방지). S2bCopy 동일 idiom.
        spec = read_json_node(ctx.store, f"{base}/rough/layout.spec.json")
        spec.setdefault("copy", {})
        for lang, text in notices.items():
            spec["copy"].setdefault(lang, {})
            spec["copy"][lang]["disclosure"] = text
        spec.setdefault("slots", [])
        logo_slot = next((s for s in spec["slots"] if s.get("role") == "logo"), None)
        if logo_slot is None:
            spec["slots"].append({"role": "logo", "z": 9,
                "bbox": {"x": 48, "y": 48, "w": 300, "h": 96},
                "asset_ref": "design-system/components/logo/v1.png"})
        else:
            # 기존 logo 슬롯(데모 fixture 등)에 asset_ref가 없으면 핀할 공식 로고 경로를 채운다 —
            # 없으면 어셈블러가 빈 src로 로고를 못 그린다(Mock에서 JB 로고 미표시 원인).
            logo_slot.setdefault("asset_ref", "design-system/components/logo/v1.png")
        ctx.store.put(f"{base}/rough/layout.spec.json",
                      json.dumps(spec, ensure_ascii=False), source="marker",
                      mime="application/json")
        return HarnessResult(text="브랜드·고지 요소를 배치했습니다.",
            output_path=f"{base}/design-system/components/disclosure",
            meta={"source": "marker", "step": self.name},
            events=[{"type": "artifact",
                     "path": f"{base}/design-system/components/disclosure"}])


class S3Final(PipelineStep):
    """metadata.md 확정 + 자기-크리틱 (구 _s3_final). 채점은 턴당 1회(cache, 백로그 ②)."""

    name = "S3"
    gated = True

    def run(self, ctx: StepContext) -> HarnessResult:
        base = ctx.base
        spec = read_json_node(ctx.store, f"{base}/rough/layout.spec.json")
        copy = spec.get("copy", {})
        langs = ctx.state.get("languages", ["ko"])
        # M7: 자기-크리틱 실행(자문용·비차단). 게이트 의미론은 spec §13으로 유보.
        critic = run_critic(ctx.provider, spec)
        ctx.cache[S3_CRITIC_CACHE] = critic   # 무조건부 기록(체크리스트 ④) — critic_gate가 재사용
        lines = ["---", f"languages: {langs}", "---", "# 디자인 메타데이터", ""]
        for lang in langs:
            c = copy.get(lang, {})
            lines.append(f"## {lang}")
            for k in ("headline", "body", "cta"):   # copy 키는 body (이전 'sub'는 항상 누락)
                if c.get(k):
                    lines.append(f"- {k}: {c[k]}")
        lines += ["", "## 크리틱",
                  f"- avg: {critic['avg']}", f"- pass: {critic['pass']}"]
        for k in RUBRIC:
            lines.append(f"- {k}: {critic['scores'].get(k)}")
        # 시각 적법성 메타데이터(결정론) — 글자크기·대비·고지 시인성 측정값을 기록해
        # Review가 비전 LLM 없이도 1차 판단(core/visual_rules와 동일 계산).
        vc = visual_compliance_summary(spec)
        font_note = " (bbox 높이 기반 추정 — 다행 고지는 과대추정 가능)" if vc.get("font_px_estimated") else ""
        lines += ["", "## 시각 적법성(visual_compliance)",
                  f"- passed: {vc['passed']}",
                  f"- disclosure_font_px: {vc['disclosure_font_px']}{font_note}",
                  f"- max_text_font_px: {vc['max_text_font_px']}",
                  f"- disclosure_contrast: {vc['disclosure_contrast']}",
                  f"- bg_color: {vc['bg_color']}",
                  f"- font_px_estimated: {vc.get('font_px_estimated', False)}"]
        for v in vc["violations"]:
            lines.append(f"- 위반 {v['rule']}({v['severity']}): {v['evidence']}")
        ctx.store.put(f"{base}/metadata.md", "\n".join(lines),
                      source="marker", mime="text/markdown")
        # meta.critic은 wire로 나가는 값 — CriticVerdict 봉투로 통일(spec §6).
        # metadata.md 렌더(위)는 raw 판정(critic['avg'] 등)을 그대로 사용.
        # meta["step"]은 self.name="S3"(백로그 ④) — 구 "done" 하드코딩은 wire 불가시였음
        # (게이트 정지는 _gate_result가 step을 gate로 덮고, done 분기는 오케스트레이터 meta 신규 생성).
        # "critic" 키는 게이트 정지 시 wire로 복사되므로 유지(체크리스트 ⑤, test_design_harness.py:401 핀).
        verdict = CriticVerdict.from_scores(critic).to_dict()
        return HarnessResult(text="디자인을 확정했습니다. 검토(review) 단계로 진행할 수 있습니다.",
            output_path=f"{base}/metadata.md",
            meta={"source": "marker", "step": self.name, "critic": verdict},
            events=[{"type": "artifact", "path": f"{base}/metadata.md"}])

    def critic_gate(self, ctx: StepContext) -> GateCheck:
        # 같은 턴에서 run이 반드시 선행·무조건부 기록 — KeyError는 계약 위반 신호이므로 .get 금지.
        return _visual_gate(ctx.cache[S3_CRITIC_CACHE])


# step 객체 선언이 단일 출처 — 수기 튜플과의 이름 불일치 원천 차단(spec §4.1, 체크리스트 ⑪).
STEP_CLASSES = (S0Setup, S1Rough, S2bCopy, S2aVisual, S2cBrand, S3Final)
STEPS = tuple(c.name for c in STEP_CLASSES) + (DONE,)
GATED_STEPS = tuple(c.name for c in STEP_CLASSES if c.gated)
CRITIC_STEPS = (S1Rough.name, S3Final.name)   # 7항목 시각 critic(S2b는 grounding — critic_gate 참조)
